# Generated by Django 4.2.9 on 2026-01-15 10:24

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wallets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TradingPair',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('symbol', models.CharField(db_index=True, help_text='Trading pair symbol (e.g., ETH_USDT)', max_length=20, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('min_order_size', models.DecimalField(decimal_places=18, default=Decimal('0.0001'), help_text='Minimum order size in base currency', max_digits=36)),
                ('max_order_size', models.DecimalField(decimal_places=18, default=Decimal('1000000'), help_text='Maximum order size in base currency', max_digits=36)),
                ('price_precision', models.IntegerField(default=8, help_text='Decimal places for price')),
                ('quantity_precision', models.IntegerField(default=8, help_text='Decimal places for quantity')),
                ('maker_fee', models.DecimalField(decimal_places=6, default=Decimal('0.001'), help_text='Maker fee (0.001 = 0.1%)', max_digits=10)),
                ('taker_fee', models.DecimalField(decimal_places=6, default=Decimal('0.001'), help_text='Taker fee (0.001 = 0.1%)', max_digits=10)),
                ('last_price', models.DecimalField(blank=True, decimal_places=18, max_digits=36, null=True)),
                ('price_change_24h', models.DecimalField(blank=True, decimal_places=4, help_text='24h price change percentage', max_digits=10, null=True)),
                ('high_24h', models.DecimalField(blank=True, decimal_places=18, max_digits=36, null=True)),
                ('low_24h', models.DecimalField(blank=True, decimal_places=18, max_digits=36, null=True)),
                ('volume_24h', models.DecimalField(blank=True, decimal_places=18, help_text='24h volume in base currency', max_digits=36, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('base_currency', models.ForeignKey(help_text='Currency being traded', on_delete=django.db.models.deletion.PROTECT, related_name='base_pairs', to='wallets.currency')),
                ('quote_currency', models.ForeignKey(help_text='Currency used for pricing', on_delete=django.db.models.deletion.PROTECT, related_name='quote_pairs', to='wallets.currency')),
            ],
            options={
                'verbose_name': 'Trading Pair',
                'verbose_name_plural': 'Trading Pairs',
                'ordering': ['symbol'],
                'unique_together': {('base_currency', 'quote_currency')},
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_type', models.CharField(choices=[('limit', 'Limit Order'), ('market', 'Market Order')], max_length=10)),
                ('side', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=4)),
                ('price', models.DecimalField(blank=True, decimal_places=18, help_text='Limit price (null for market orders)', max_digits=36, null=True)),
                ('quantity', models.DecimalField(decimal_places=18, help_text='Original order quantity', max_digits=36, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('filled_quantity', models.DecimalField(decimal_places=18, default=Decimal('0'), help_text='Quantity filled so far', max_digits=36)),
                ('status', models.CharField(choices=[('open', 'Open'), ('partial', 'Partially Filled'), ('filled', 'Filled'), ('cancelled', 'Cancelled')], default='open', max_length=20)),
                ('time_in_force', models.CharField(choices=[('GTC', 'Good Till Cancelled'), ('IOC', 'Immediate Or Cancel'), ('FOK', 'Fill Or Kill')], default='GTC', max_length=10)),
                ('client_order_id', models.CharField(blank=True, help_text='Client-provided order ID', max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('filled_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('trading_pair', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='trading.tradingpair')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=18, max_digits=36)),
                ('quantity', models.DecimalField(decimal_places=18, max_digits=36)),
                ('quote_quantity', models.DecimalField(decimal_places=18, help_text='price * quantity', max_digits=36)),
                ('buyer_fee', models.DecimalField(decimal_places=18, default=Decimal('0'), max_digits=36)),
                ('seller_fee', models.DecimalField(decimal_places=18, default=Decimal('0'), max_digits=36)),
                ('buyer_is_maker', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('buy_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='buy_trades', to='trading.order')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buy_trades', to=settings.AUTH_USER_MODEL)),
                ('sell_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sell_trades', to='trading.order')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sell_trades', to=settings.AUTH_USER_MODEL)),
                ('trading_pair', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trades', to='trading.tradingpair')),
            ],
            options={
                'verbose_name': 'Trade',
                'verbose_name_plural': 'Trades',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['trading_pair', '-created_at'], name='trading_tra_trading_a32f40_idx'), models.Index(fields=['buyer', '-created_at'], name='trading_tra_buyer_i_0e2b22_idx'), models.Index(fields=['seller', '-created_at'], name='trading_tra_seller__450579_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['trading_pair', 'side', 'status', 'price'], name='trading_ord_trading_1521e9_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', 'status'], name='trading_ord_user_id_d93b91_idx'),
        ),
    ]
