# Generated by Django 4.2.9 on 2026-01-23 06:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KYCDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('passport', 'Passport'), ('national_id', 'National ID'), ('drivers_license', "Driver's License"), ('selfie', 'Selfie with ID'), ('proof_of_address', 'Proof of Address'), ('bank_statement', 'Bank Statement'), ('utility_bill', 'Utility Bill'), ('source_of_funds', 'Source of Funds')], max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('file', models.FileField(upload_to='kyc_documents/%Y/%m/')),
                ('file_hash', models.CharField(blank=True, max_length=64)),
                ('original_filename', models.CharField(max_length=255)),
                ('file_size', models.IntegerField(default=0)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('document_number', models.CharField(blank=True, max_length=100)),
                ('issuing_country', models.CharField(blank=True, max_length=100)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('extracted_data', models.JSONField(blank=True, default=dict)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'kyc_documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KYCLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('unverified', 'Unverified'), ('basic', 'Basic'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=20, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('daily_withdrawal_limit', models.DecimalField(decimal_places=2, max_digits=20)),
                ('monthly_withdrawal_limit', models.DecimalField(decimal_places=2, max_digits=20)),
                ('daily_deposit_limit', models.DecimalField(decimal_places=2, max_digits=20)),
                ('can_trade', models.BooleanField(default=True)),
                ('can_withdraw_crypto', models.BooleanField(default=False)),
                ('can_withdraw_fiat', models.BooleanField(default=False)),
                ('can_use_p2p', models.BooleanField(default=False)),
                ('requires_email', models.BooleanField(default=True)),
                ('requires_phone', models.BooleanField(default=False)),
                ('requires_id_document', models.BooleanField(default=False)),
                ('requires_selfie', models.BooleanField(default=False)),
                ('requires_proof_of_address', models.BooleanField(default=False)),
                ('requires_source_of_funds', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'kyc_levels',
                'ordering': ['daily_withdrawal_limit'],
            },
        ),
        migrations.CreateModel(
            name='KYCProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('expired', 'Expired'), ('suspended', 'Suspended')], default='not_started', max_length=20)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('nationality', models.CharField(blank=True, max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('phone_verified', models.BooleanField(default=False)),
                ('address_line1', models.CharField(blank=True, max_length=255)),
                ('address_line2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('email_verified_at', models.DateTimeField(blank=True, null=True)),
                ('phone_verified_at', models.DateTimeField(blank=True, null=True)),
                ('identity_verified_at', models.DateTimeField(blank=True, null=True)),
                ('address_verified_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('risk_score', models.IntegerField(default=0)),
                ('is_pep', models.BooleanField(default=False)),
                ('is_sanctioned', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('current_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='profiles', to='kyc.kyclevel')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kyc_reviews', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'kyc_profiles',
            },
        ),
        migrations.CreateModel(
            name='KYCVerificationRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_type', models.CharField(choices=[('basic', 'Basic Verification'), ('intermediate', 'Intermediate Verification'), ('advanced', 'Advanced Verification'), ('resubmission', 'Resubmission')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_review', 'In Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('more_info', 'More Info Required')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('additional_info_request', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_kyc_requests', to=settings.AUTH_USER_MODEL)),
                ('documents', models.ManyToManyField(related_name='verification_requests', to='kyc.kycdocument')),
                ('kyc_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_requests', to='kyc.kycprofile')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_kyc_requests', to=settings.AUTH_USER_MODEL)),
                ('target_level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='verification_requests', to='kyc.kyclevel')),
            ],
            options={
                'db_table': 'kyc_verification_requests',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.AddField(
            model_name='kycdocument',
            name='kyc_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='kyc.kycprofile'),
        ),
        migrations.AddField(
            model_name='kycdocument',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='KYCAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('profile_created', 'Profile Created'), ('document_uploaded', 'Document Uploaded'), ('document_approved', 'Document Approved'), ('document_rejected', 'Document Rejected'), ('verification_submitted', 'Verification Submitted'), ('verification_approved', 'Verification Approved'), ('verification_rejected', 'Verification Rejected'), ('level_upgraded', 'Level Upgraded'), ('level_downgraded', 'Level Downgraded'), ('profile_suspended', 'Profile Suspended')], max_length=30)),
                ('description', models.TextField()),
                ('old_value', models.JSONField(blank=True, default=dict)),
                ('new_value', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('kyc_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='kyc.kycprofile')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kyc_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'kyc_audit_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
